<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>INDEX</title>
</head>
<body>
    <?php
      echo '<h1> view: index.phtml </h1>';
      echo '<ul>';
      foreach($dados as $indice => $valor){
        echo '<li>';
        echo $indice.' - '.$valor;
        echo '</li>';
      }
      echo '</ul>';
    ?>
</body>
</html>